---

- hosts: appservers
  remote_user: "{{ appuser }}"
  vars_files:
      - secrets.yml
  tasks:
    - name: create supervisor logging directory
      file: path=/var/log/supervisord state=directory owner={{ appuser }} group={{ appuser }} mode=0770
      sudo: yes

    - name: create cron logfiles
      copy: content='' dest=/var/log/{{ item }} force=no owner={{ appuser }} group={{ appuser }} mode=0660
      with_items:
          - delete_old_mail.log
          - sync_licenses.log
      sudo: yes

    - cron: name="delete old emails"
            special_time="daily"
            user="{{ appuser }}"
            job="cd {{ appdir }}; DJANGO_SETTINGS_MODULE=gchatautorespond.settings {{ venv }}/bin/python delete_old_mail.py >> /var/log/delete_old_mail.log 2>&1"
            cron_file="gchat_delete_old_mail"
      sudo: yes

    - cron: name="sync licenses"
            minute="30"
            hour="10"
            user="{{ appuser }}"
            job="cd {{ appdir }}; DJANGO_SETTINGS_MODULE=gchatautorespond.settings {{ venv }}/bin/python sync_licenses.py >> /var/log/sync_licenses.log 2>&1"
            cron_file="gchat_sync_licenses"
      sudo: yes

    - name: install app dependencies
      pip: requirements={{ appdir }}/requirements.txt virtualenv={{ venv }}
      register: pip_result
      changed_when: '"Successfully installed" in pip_result.stdout'


    - name: perform migrations
      command: "{{ venv }}/exec python manage.py migrate --noinput"
      args:
          chdir: "{{ appdir }}"
      register: migrate_result
      changed_when: '"No migrations to apply." not in migrate_result.stdout'

    - include: roles/runapp/tasks/ensure_superuser.yml

    - name: shut down an existing djsupervisor
      command: "{{ venv }}/exec python manage.py supervisor shutdown"
      ignore_errors: yes
      args:
          chdir: "{{ appdir }}"

    - name: start djsupervisor
      command: "{{ venv }}/exec python manage.py supervisor --daemonize"
      args:
          chdir: "{{ appdir }}"
      register: result
      # Sometimes the socket isn't released right away.
      until: result.stdout.find("Another program is already listening") == -1
      retries: 3
      delay: 2
